README.md, project/MicroService.scala, test/repositories/MessageRepositorySpec.scala
=> Ccalc 2255

app/controllers/RegistrationController.scala
@milena-valchanova @shridhaarchippaa please review and let me know comments if any.
=> remove commented code

app/controllers/RegistrationController.scala, app/services/AuditEvents.scala
@milena-valchanova @shridhaarchippaa
=> Change audit

app/controllers/RegistrationController.scala, app/services/RegistartionService.scala, test/controllers/RegistrationControllerSpec.scala
@shridhaarchippaa @roma-silimcano
=> Refactor audit

app/models/Registration.scala, app/repositories/RegistartionRepository.scala, test/fixtures/RegistrationData.scala
=> Save DOB in db

app/controllers/RegistrationController.scala, app/services/AuditEvents.scala, test/controllers/RegistrationControllerSpec.scala, test/fixtures/RegistrationData.scala
=> Audit DOBs

app/controllers/EmailCaptureController.scala, app/repositories/MessageRepository.scala, app/services/EmailService.scala, app/services/MessageService.scala
=> Remove logger.info

conf/application-logger.xml
=> Update logging level

app/controllers/EmailCaptureController.scala, app/controllers/RegistrationController.scala, app/services/EmailService.scala, test/controllers/EmailCaptureControllerSpec.scala, test/controllers/RegistrationControllerSpec.scala, test/services/EmailServiceSpec.scala
=> Updated specific internal server error

conf/application.conf
=> removed overridden logger level from app.conf

conf/logback.xml
=> Updated logger levels

app/services/EmailService.scala
@shridhaarchippaa @milena-valchanova Please review and merge if happy
Thanks
=> Updated endpoints for validating and sending emails

app/config/ApplicationConfig.scala, app/controllers/RegistrationController.scala, test/controllers/EmailCaptureControllerSpec.scala, test/controllers/RegistrationControllerSpec.scala
=> Fix issues

app/repositories/MessageRepository.scala, app/repositories/RegistartionRepository.scala, app/services/SchedulerService.scala, scalastyle-config.xml
=> Resolve some scalastyle warnings

app/config/ApplicationConfig.scala, app/config/CcGlobal.scala, app/repositories/MessageRepository.scala, app/repositories/RegistartionRepository.scala, app/services/MessageService.scala, app/services/RegistartionService.scala, app/services/SchedulerService.scala, conf/mail.conf, test/config/ApplicationConfigSpec.scala, test/services/MessageServiceSpec.scala, test/services/RegistartionServiceSpec.scala
@Muhammad-Ali-Ahmad @bentaylor12 @RonanOCarroll
=> Ccalc 2818

app/config/ApplicationConfig.scala, app/config/CcGlobal.scala, app/controllers/RegistrationController.scala, app/models/Registration.scala, app/repositories/MessageRepository.scala, app/repositories/RegistrationRepository.scala, app/services/RegistartionService.scala, app/services/RegistrationService.scala, app/services/SchedulerService.scala, conf/application.conf, conf/mail.conf, test/controllers/RegistrationControllerSpec.scala, test/fixtures/RegistrationData.scala, test/services/RegistartionServiceSpec.scala, test/services/SchedulerServiceSpec.scala
=> Ccalc 2812

app/services/AuditEvents.scala, app/services/SchedulerService.scala, test/services/SchedulerServiceSpec.scala
=> Email logs

app/controllers/RegistrationController.scala
=> Audit correctly dob for csi

project/build.properties
DDCNLS-1376 : Upgraded sbt version 0.11.15
=> DDCNLS-1376 : Upgraded sbt version 0.11.15

app/config/ApplicationConfig.scala, app/config/CcGlobal.scala, app/repositories/FilterHelper.scala, app/repositories/MessageRepository.scala, app/repositories/RegistrationRepository.scala, app/services/MessageService.scala, app/services/RegistrationService.scala, conf/mail.conf, test/repository/FilterHelperSpec.scala, test/services/MessageServiceSpec.scala
=> Count emails in db per age group
